package com.example.segundaeva.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFFA01DAB)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD6F9)
val md_theme_light_onPrimaryContainer = Color(0xFF37003C)
val md_theme_light_secondary = Color(0xFF005EB2)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD5E3FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001B3C)
val md_theme_light_tertiary = Color(0xFF006C48)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF5FFDB9)
val md_theme_light_onTertiaryContainer = Color(0xFF002113)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1E1A1D)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1E1A1D)
val md_theme_light_surfaceVariant = Color(0xFFEDDEE8)
val md_theme_light_onSurfaceVariant = Color(0xFF4D444B)
val md_theme_light_outline = Color(0xFF7F747C)
val md_theme_light_inverseOnSurface = Color(0xFFF7EEF2)
val md_theme_light_inverseSurface = Color(0xFF342F32)
val md_theme_light_inversePrimary = Color(0xFFFFA9FD)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFA01DAB)
val md_theme_light_outlineVariant = Color(0xFFD0C3CC)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFA9FD)
val md_theme_dark_onPrimary = Color(0xFF590061)
val md_theme_dark_primaryContainer = Color(0xFF7E0089)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD6F9)
val md_theme_dark_secondary = Color(0xFFA7C8FF)
val md_theme_dark_onSecondary = Color(0xFF003061)
val md_theme_dark_secondaryContainer = Color(0xFF004788)
val md_theme_dark_onSecondaryContainer = Color(0xFFD5E3FF)
val md_theme_dark_tertiary = Color(0xFF3AE09F)
val md_theme_dark_onTertiary = Color(0xFF003824)
val md_theme_dark_tertiaryContainer = Color(0xFF005236)
val md_theme_dark_onTertiaryContainer = Color(0xFF5FFDB9)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1E1A1D)
val md_theme_dark_onBackground = Color(0xFFE9E0E4)
val md_theme_dark_surface = Color(0xFF1E1A1D)
val md_theme_dark_onSurface = Color(0xFFE9E0E4)
val md_theme_dark_surfaceVariant = Color(0xFF4D444B)
val md_theme_dark_onSurfaceVariant = Color(0xFFD0C3CC)
val md_theme_dark_outline = Color(0xFF998D96)
val md_theme_dark_inverseOnSurface = Color(0xFF1E1A1D)
val md_theme_dark_inverseSurface = Color(0xFFE9E0E4)
val md_theme_dark_inversePrimary = Color(0xFFA01DAB)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFA9FD)
val md_theme_dark_outlineVariant = Color(0xFF4D444B)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF91009D)

/*
val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)*/